"""
##### Description
This module features an image processing program that applies grayscale 
transformation to batches of images. These images are retrieved from a 
list of URLs pointing to public domain images available on the Web. 
The program downloads each image and converts it to grayscale. In the 
current version, the list of image URLs is generated by a lightweight 
generative artificial intelligence (AI) model.

##### Author  
[Everton Cavalcante](mailto:everton.cavalcante@ufrn.br)

##### Date    
September 24, 2025
"""